### ISSUE TITLE
[SUGGESTION] Add class attribute to tasks

### ISSUE THREAD

**Issue by Edison946** [Tuestech/code#12]
Add back the class feature where each tasks is assigned what class it is for

**Comment by USSiamaboat** [comment]
In progress.

**Comment by USSiamaboat** [comment]
https://github.com/Tuestech/code/pull/24
Infrastructure in progress

**Comment by USSiamaboat** [comment]
Priority feature

**Comment by USSiamaboat** [comment]
Will be implemented as a feature with #33 issue will be kept open until fixed.

**Comment by USSiamaboat** [comment]
> Will be implemented as a feature with #33 issue will be kept open until fixed.

Changes in plan, will be implemented #33 to ensure timely completion of higher priority issues

**Comment by USSiamaboat** [comment]
Will be implemented in rewrite

**Comment by USSiamaboat** [comment]
No longer maintained
